### ISSUE TITLE
Support for SSR

### ISSUE THREAD

**Issue by wesbos** [wenliangdai/react-audioplayer#1]
Hey - thanks for this component - giving it a shot on my podcast website. 

I'm doing SSR with this app, so I need a way to exclude this component if window and document aren't present. Any way to do this?

**Comment by wesbos** [comment]
This is how I ended up doing it:

```
const isBrowser = typeof window !== 'undefined';
const Audio = isBrowser ? require('react-audioplayer').default : null;
```

then in my render method:

```
{ Audio && <Audio controls playlist={[{src: show.url, name: show.title}]}></Audio> }
```

**Comment by wenliangdai** [comment]
Awesome! I think your way to exclude the component is good, i.e. doing it outside of the component. BTW, if you're interested, more APIs will be added in the next release to make it more controllable.
