### ISSUE TITLE
Multiple Players

### ISSUE THREAD

**Issue by alienintheheights** [wenliangdai/react-audioplayer#4]
I have multiple players on a page and I would like to be able to pause one when I start another. I know I can use a ref on the Audio component to get a hook for pausing that component. But it seems like the ref function only fires when the component unloads. If it fired on load then I could register it and control it with clickHandlers. Am I missing something?

ref={audioComponent => { this.audioComponent = audioComponent; }}

**Comment by wenliangdai** [comment]
What do you mean by "the ref function only fires when the component unloads"? If you have more than one players, one way to achieve that is storing refs of them in componentDidMount lifecycle hook. Then you can control them by dispatching relative events.
